services:
  db:
    image: postgres:15
    container_name: market_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser 
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: market_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # OPTIONAL database management, very small
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
